---
abstract: 'Group sets transitively'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-EquivalenceSets
provides:
  Algorithm::EquivalenceSets:
    file: lib/Algorithm/EquivalenceSets.pm
    version: 1.100870
requires:
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  YAML: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Algorithm-EquivalenceSets
  homepage: http://search.cpan.org/dist/Algorithm-EquivalenceSets/
  repository: http://github.com/hanekomu/Algorithm-EquivalenceSets
version: 1.100870
